### ISSUE TITLE
Provisioning Devstack (mitaka) + Contrail in Multi-node topology 

### ISSUE THREAD

**Issue by raviprasad239** [zioc/contrail-devstack-plugin#16]
How to provision Devstack + OpenContrail in Multi Node topology ?

**Comment by Doude** [comment]
I never tried but you can look at the [devstack multi-node documentation]( http://docs.openstack.org/developer/devstack/guides/multinode-lab.html) if you like to setup on control & compute node and another compute node.
For contrail, you should only enable the vrouter service on the _only_ compute node:
>disable_service disco api-srv schema svc-mon control collector analytic-api query-engine dns named ui-webs ui-jobs
>enable_service vrouter

**Comment by raviprasad239** [comment]
I am able to setup multi node step with above configuration.
But VM creation is failing on remote compute node if "neutron" is not enabled (ENABLED_SERVICES).
On enabling neutron on compute node, VM creation is successful, but default route was not created.
However default route was created when VM was spawned on Controller's compute node.
Any suggestions, how we can create default route in newly spawned VM for compute node ? 
Also does contrail creates tunnel (VxLAN or any other) among compute node by default?

**Comment by Doude** [comment]
Good. I need try myself to get why it's need to enable Neutron on the compute to spawn the VM.
I did not understand what you mean by `default route is not created`. Did you attach the VM to a private network? If yes, the VM get a fixed IP and a default route to the private network gateway? Did you try to associate a floating IP from the public network to the VM fixed IP?
I think Contrail use by default that encapsulation order `MPLSoGRE, MPLSoUDP then VxLAN` which could be customized.

**Comment by raviprasad239** [comment]
1) I created one new network (from OpenStack dashboard) "nw1" and associated this network with subnet 192.168.1.0/24.
2) I attached 5 VMs to nw1.
3) These VMs are spawned across compute Node.
4) All 5 VMs spawned got fixed if from subnet 192.168.1.0/24.
5) But for all the VMs attached to Compute Node, I executed route command in newly spawned VM, but it was not having default route.
6) However for the VMs, spawned on Controller + Compute node (A node with all component), was having default route (gw) as 192.168.1.1. I was expecting same for VMs spawned on compute node.

I also observed that VMs spawned on  Controller + Compute node, has link local address for newly spawned VM as 169.254.0.4 . But On compute node, even if VMs are spawned but link local address for spawned VMs were not created.
I checked tap interface status in the http agent introspect (http://<compute-node-ip>:8085/Snh_ItfReq?name=), which shows 	vrf_name as "--ERROR--" , active as "Inactive" and mdata_ip_addr as "0.0.0.0".
However these entry are proper for Controller + Compute node.   
"vif --list" is not displaying any thing in any node, do we need to do some additional configuration for "vif" tool?

**Comment by Doude** [comment]
Are you logged on the [opencontrail slack chat](http://slack.opencontrail.org/)?

**Comment by raviprasad239** [comment]
I am able to set multi node topology.
