### ISSUE TITLE
Doesn't build on clean Ubuntu 14.04

### ISSUE THREAD

**Issue by Ezeon** [zioc/contrail-devstack-plugin#21]
I did the following:
1) Installed a clean image of Ubuntu 14.04
2) apt install git
3) typed exactly the instructed commands

Result:
Build is failing on opencontrail:
2016-09-04 16:59:16.888 | /opt/stack/contrail/devstack/lib/contrail_config: line 268: syntax error in conditional expression: unexpected token `|'

Log file attached.

[build failure.txt](https://github.com/zioc/contrail-devstack-plugin/files/454015/build.failure.txt)

**Comment by zioc** [comment]
Sorry, I made a typo in last commit...
