### ISSUE TITLE
(Solved) import error during ./stack.sh

### ISSUE THREAD

**Issue by alexiei** [zioc/contrail-devstack-plugin#22]
Hi,
I found an import error during my installation that I solved in this way:

sudo su
pip install pydot

Now all works

**Comment by zioc** [comment]
Hi,

Could you elaborate a little bit? Where did you observe the import error?
I haven't yet observed this kind of error...

**Comment by alexiei** [comment]
Yes, sorry.

After the launch of ./stack.sh the process went in error.

During the logs analysis process I found this:
"ImportError: No module named pydot"

**Comment by Doude** [comment]
Hi, Do you still hit that issue?

**Comment by alexiei** [comment]
Hi Ed!

No, I resolved all my problems with the commercial version of OpenContrail (3.2)

Thanks a lot for all your support, I really appreciate it

Alessandro

**Comment by Doude** [comment]
Ok, I close that issue.
