### ISSUE TITLE
Anlytical Node Down

### ISSUE THREAD

**Issue by DEEM78** [zioc/contrail-devstack-plugin#55]
Hello

Despite an installation that went successfuly, I am facing two issues:

- When trying to create VM via horizon using the admin account, the list of avaialable network are hidden (on the menu I see that I have 4 network available but non are list below). I guess it is an authorization/right access issue but I don't know why it is the case as I am using a standard configuration without modifying the initial setup 

- The analytical api seems to be down eventhough the service is active and running (output of systemctl). And what is disturbing is that via the webUI, menu Monitor-infrastructure-Control Nodes, the status show is down. 
The journalctl -u devstack@contrail-analytic.service  is showing the following ERROR

07/04/2018 11:46:48 PM [contrail-analytics-api] [ERROR]: SANDESH: [DROP: WrongClientSMState] NodeStatusUVE: data = <<  name = keats  process_status = [ <<  module_id = contrail-analytics-api  instance_id = 0  state = Non-Functional  connection_infos = [ <<  type = UvePartitions  name = UVE-Aggregation  server_addrs = [  ]  status = Up  >>, <<  type = Collector  name =   server_addrs = [ ,  ]  status = Down  description = none to Idle on EvStart  >>, <<  type = Redis-UVE  name = 10.194.67.34:6379  server_addrs = [ 10.194.67.34:6379,  ]  status = Up  >>,  ]  description = Collector connection down  >>,  ]  >>
Jul 05 10:22:36 keats contrail-analytics-api[121257]: 07/05/2018 10:22:36 AM [contrail-analytics-api] [ERROR]: SANDESH: [DROP: NoSession] __default__ [SYS_INFO]: AnalyticsApiStats: api_stats = <<  operation_type = GET  remote_ip = 10.194.67.34  object_type = vrouter  request_url = http://10.194.67.34:8081/analytics/uves/vrouter/%2A?cfilt=NodeStatus:process_status  response_time_in_usec = 4324  response_size_objects = 1  response_size_bytes = 583  resp_code = 200  useragent = python-requests/2.18.2  node = keats  >>

your help is appreciated 

Thank you

**Comment by DEEM78** [comment]
Hello Doude

Below my local.conf. Thank you for you your help

Regards

[[local|localrc]]
ADMIN_PASSWORD=admin
DATABASE_PASSWORD=root
RABBIT_PASSWORD=openstack
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=admin

HOST_IP=10.194.67.34
CONTROLLER=10.194.67.34
SERVICE_HOST=$CONTROLLER
MYSQL_HOST=$HOST_IP
RABBIT_HOST=$HOST_IP

FORCE=yes
RECLONE=False
VERBOSE=True

GIT_BASE=https://git.openstack.org
DEST=~/openstack

LOGFILE=$DEST/logs/stack.sh.log
LOGDIR=$DEST/logs
LOGDAYS=2


disable_service dstat
disable_service n-novnc
disable_service n-cauth
disable_service tempest
enable_service placement_api
enable_service placement
enable_service heat

ENABLED_SERVICES+=neutron,q-agt,q-dhcp,q-l3,q-meta

KEYSTONE_SECURITY_COMPLIANCE_ENABLED=False

enable_plugin contrail https://github.com/zioc/contrail-devstack-plugin.git

VHOST_INTERFACE_NAME=eno1
Q_L3_ENABLED=True
VGW_MASQUERADE=True

Q_USE_SECGROUP=False
LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver

enable_plugin networking-bgpvpn https://git.openstack.org/openstack/networking-bgpvpn.git stable/pike
NETWORKING_BGPVPN_DRIVER="BGPVPN:OpenContrail:networking_bgpvpn.neutron.services.service_drivers.opencontrail.opencontrail.OpenContrailBGPVPNDriver:default"

**Comment by Doude** [comment]
`local.conf` looks good. Are you using master branch of Contrail with Pike OpenStack release?

From the analytics logs, the problem seems to coming from the collector. Can you check the status and logs of `devstack@contril-collector` service?

About network list not shown, you mean you can see networks in the horizon network dashboard but you can not see any network in the VM create wizard? Is it the same issue with a non admin user? Did you tried to boot a VM through the CLI (I'm not familiar with UI, I don't use it)

**Comment by Doude** [comment]
Could you also share devstack log file `$DEST/logs/stack.sh.log`, please?

**Comment by DEEM78** [comment]
The network list is shown correctly using the CLI, it is an UI/Right access problem I guess. Not too critcial anyway

Yes I am using Pike with the master contrail (tried in two months ago with queens using the same local.conf but didn't work out for me)0

Below the collector logs 

Thank you for your help

Regards

Jul 12 11:04:04 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:036.168 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILE2018-07-12 11:04:04,441:125249(0x7f254bbfe700):ZOO_DEBUG@zookeeper_process@2218: Got ping response in 0 ms
Jul 12 11:04:05 keats contrail-collector[125249]: D
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:036.621 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:037.175 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:037.876 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:038.398 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:038.847 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:039.315 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:039.728 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:040.195 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:040.391 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:040.579 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:040.762 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:040.944 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:041.125 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:041.305 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:041.486 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:041.668 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:041.850 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:042.031 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:042.214 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:042.395 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:02:042.573 CEST  keats [Thread 139798106826496, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:922.677 CEST  keats [Thread 139798266214144, Pid 125249]: SANDESH: Sending: LEVEL: [ INVALID ] -> [ SYS_DEBUG ] : 2200
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:923.270 CEST  keats [Thread 139798266214144, Pid 125249]: SANDESH: Sending: LEVEL: [ SYS_DEBUG ] -> [ INVALID ] : 0
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:926.743 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: ObjectTableInsert: Addition of keats:Analytics:contrail-collector:0, message UUID 2540506b-6f4b-43e0-8ede-d4e59754ed4a ObjectGeneratorInfo into table ObjectValueTable FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:927.077 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: MessageTableOnlyInsert: Addition of message: SandeshModuleClientTrace, message UUID: 2540506b-6f4b-43e0-8ede-d4e59754ed4a COLUMN FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:928.230 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: ObjectTableInsert: Addition of keats:Analytics:contrail-collector:0, message UUID defadb6f-7f9d-43c5-9b4f-301c1b323e3f ObjectGeneratorInfo into table ObjectValueTable FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:928.941 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: MessageTableOnlyInsert: Addition of message: SandeshModuleClientTrace, message UUID: defadb6f-7f9d-43c5-9b4f-301c1b323e3f COLUMN FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:930.120 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:930.881 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:931.467 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:931.998 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:932.518 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:933.039 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:933.556 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:934.071 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:934.583 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:935.123 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:935.620 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:936.090 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, msg_type_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:936.604 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:936.822 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:937.033 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
Jul 12 11:04:05 keats contrail-collector[125249]: 2018-07-12 Thu 11:04:05:937.243 CEST  keats [Thread 139798257817344, Pid 125249]: keats:Global: StatTableWrite: Addition of ModuleClientState, tx_msg_agg into table StatsTableV4 FAILED
