### ISSUE TITLE
can`t build with different errors.

### ISSUE THREAD

**Issue by fxpester** [zioc/contrail-devstack-plugin#8]
Hello zioc, Im failing to build your plugin for several times with different branchs of devstack. errors was like `"AttributeError: 'VncApi' object has no attribute '_tenant_name'"` can't figure them out.

Can you share some details about working setup ? What Ubuntu version do you use (14.04.1, or 14.04.2)? How many NICs you have ? What branch of devstack do you use ? Maybe you can share working local.conf ? thank you.

**Comment by zioc** [comment]
Hi

You're proably hitting this bug which occurs while using contrail aginst mitaka and subsequent releases:

https://bugs.launchpad.net/opencontrail/+bug/1579806

Please cheery pick the corresponding change, and try to run stack.sh again:

cd /opt/stack/contrail/controller
git fetch https://review.opencontrail.org/Juniper/contrail-controller refs/changes/10/20010/3 && git cherry-pick FETCH_HEAD

cd ~/devstack
./stack.sh

I may update the README consequently, as fix hasn't been merged yet.
Regards
